export const DB = {

  MAX_LENGTH_LASTNAME: 50,
  MAX_LENGTH_NAME: 50,
  MAX_LENGTH_USERNAME: 100,
  MAX_LENGTH_EMAIL: 100,
  MAX_LENGTH_PASSWORD: 50,
  MAX_LENGTH_COUNTRY: 75,
  MAX_LENGTH_ROLE: 20,

}